# -*- coding: utf-8 -*-
"""
Digify — conteúdo dos três idiomas.
Editar SÓ este arquivo para mudar textos. Depois rodar:  python3 _build/build.py
"""

SITE = "https://digify.live"
PHONE = "+5511989911000"
PHONE_LABEL = "(11) 98991-1000"

LOGOS = ["Vai-Vai", "Dailus", "TMiranda", "HiperSkin", "Rache Aqui",
         "Avalone Studio Imóveis", "Imóveis VIP", "FullSale", "Squad Shop", "Repórter Hoje"]

# ---------------------------------------------------------------- PT-BR
PT = {
  "code": "pt-BR", "short": "PT", "dir": "", "og": "pt_BR",
  "title": "Digify | Criação de Sites, Sistemas e SEO | Agência Web no Brasil",
  "desc": "Agência web full-stack: criação de sites, sistemas sob medida e SEO. Mais de 10 anos e 300 projetos levando empresas ao topo do Google.",
  "form_name": "proposta-pt",
  "wa_text": "Quero+um+diagn%C3%B3stico+gratuito",
  "skip": "Pular para o conteúdo",
  "nav": [("#servicos","Serviços"),("/portfolio/","Portfólio"),("/blog/","Blog"),("/sobre/","Sobre")],
  "cta_nav": "Solicitar proposta",
  "menu_open": "Abrir menu", "menu_close": "Fechar menu",
  "sw_label": "Acender ou apagar a luz do site", "sw_title": "Acender / apagar",
  "lang_label": "Idioma do site",
  "tablist": "Destaques da Digify",
  "slides": [
    {"c":"flame","c2":"ultra",
     "eyebrow":"Agência web full-stack · Brasil",
     "h":"O <em class=\"hl\">primeiro</em> resultado leva quase tudo.",
     "tag":"h1",
     "lede":"Enquanto você lê isso, alguém procura exatamente o que você vende. Fazemos SEO técnico, conteúdo e autoridade para que a resposta seja o seu site — e não o do concorrente.",
     "cta1":"Solicitar proposta","cta2":"Como fazemos SEO","cta2_href":"/servicos/seo/",
     "facts":[("#1–3","posição orgânica"),("+340%","tráfego em 12 meses"),("300+","projetos entregues")],
     "panel":"rank",
     "p_query":"o que você vende + sua cidade","p_you":"Sua empresa","p_tag":"posição 1",
     "p_cap":"Posição orgânica média dos clientes Digify entre #1 e #3 nos primeiros 6 meses de projeto."},
    {"c":"cyan","c2":"jade",
     "eyebrow":"Sistemas sob medida · APIs · Automação",
     "h":"Traga a ideia. Devolvemos o <em class=\"hl\">sistema inteiro</em>.",
     "tag":"h2",
     "lede":"Você descreve o problema em português, não em requisito técnico. A gente desenha a arquitetura, escreve o código, integra com o que já existe e coloca no ar — com entrega toda semana para você acompanhar.",
     "cta1":"Quero meu sistema","cta2":"Ver como funciona","cta2_href":"/servicos/sistemas/",
     "facts":[("6 sem.","até o primeiro MVP"),("Semanal","ciclo de entrega"),("100%","do código é seu")],
     "panel":"build",
     "p_top":"briefing recebido",
     "p_idea":"“Preciso controlar pedidos e estoque num lugar só, e emitir nota sem redigitar nada.”",
     "p_mods":["Pedidos","Estoque","Emissão fiscal","Relatórios","Integração ERP","Acessos e perfis"],
     "p_cap":"Arquitetura, código, testes e deploy. Você acompanha o progresso em tempo real."},
    {"c":"violet","c2":"pink",
     "eyebrow":"Criação de sites · Design sob medida",
     "h":"Seu site, do seu jeitinho. No ar em <em class=\"hl\">tempo recorde</em>.",
     "tag":"h2",
     "lede":"Nada de template pronto com o logo trocado. Desenhamos do zero, no tom da sua marca e com a estrutura que o seu negócio pede. Rápido porque o processo já rodou mais de 300 vezes — não porque cortamos caminho.",
     "cta1":"Quero meu site","cta2":"Ver o processo","cta2_href":"/servicos/criacao-de-sites/",
     "facts":[("10 dias","para uma landing no ar"),("98/100","nota média no PageSpeed"),("Zero","tema pronto reaproveitado")],
     "panel":"site",
     "p_url":"seudominio.com.br","p_cap":"sua identidade, não a nossa"},
  ],
  "tabs":[("01 · SEO","Aparecer antes do concorrente"),
          ("02 · Sistemas","Da ideia ao sistema completo"),
          ("03 · Sites","Do seu jeito, em tempo recorde")],
  "logos_label":"Empresas que confiam na Digify",
  "nums_eyebrow":"Resultado","nums_h":"Número, não adjetivo.",
  "nums":[("flame","#1–3","Posição orgânica média","Nos primeiros 6 meses de projeto de SEO."),
          ("ultra","+340%","Crescimento de tráfego","Média dos projetos de SEO em 12 meses."),
          ("jade","98/100","Nota no PageSpeed","Média dos sites que entregamos.")],
  "svc_eyebrow":"O que fazemos","svc_h":"Seis frentes, um objetivo.",
  "svc_lede":"Cada projeto começa pelo problema do negócio — não pelo catálogo de serviços.",
  "svc_cta":"Falar sobre o meu caso","svc_go":"Ver serviço",
  "svcs":[("flame","Sites","Criação de sites","/servicos/criacao-de-sites/","Sites institucionais, landing pages e e-commerces ultrarrápidos, responsivos e desenhados para transformar visita em cliente."),
          ("ultra","Apps","Desenvolvimento de apps","/servicos/desenvolvimento-de-apps/","Aplicativos iOS e Android com design intuitivo e integração com APIs. Do MVP ao produto final, com entregas semanais."),
          ("jade","SEO","Agência de SEO","/servicos/seo/","Auditoria técnica, conteúdo, link building e monitoramento de posições. SEO que coloca você na frente de quem já procura."),
          ("violet","Mídia paga","Marketing digital","/servicos/marketing-digital/","Google Ads, Meta Ads e crescimento orgânico trabalhando juntos para atrair cliente qualificado e defender o ROI."),
          ("pink","E-commerce","Lojas virtuais","/servicos/ecommerce/","Alta performance, UX otimizada para conversão, integração com marketplaces e todos os principais meios de pagamento."),
          ("cyan","Sistemas","Sistemas e integrações","/servicos/sistemas/","Sistemas web sob medida, APIs e automações que eliminam trabalho manual e fazem o negócio escalar sem inchar o time.")],
  "proc_eyebrow":"Como trabalhamos","proc_h":"Diagnóstico. Plano. Código. Crescimento.",
  "steps":[("Diagnóstico","Entendemos o negócio, o mercado e os concorrentes antes de propor qualquer solução. Sem fórmula pronta."),
           ("Planejamento","Escopo, tecnologia, cronograma e indicadores definidos. Você sabe exatamente o que esperar e quando."),
           ("Execução","Desenvolvimento com atualizações semanais e acesso ao progresso em tempo real, sem caixa-preta."),
           ("Crescimento","Lançamos, medimos e otimizamos. O projeto não acaba no deploy — é ali que ele começa.")],
  "quo_eyebrow":"Clientes","quo_h":"Quem já passou por aqui.","quo_stars":"5 de 5",
  "quotes":[("flame","Há anos o Vai-Vai atua em parceria com a Digify. Fizemos diversos projetos, de sites a ações pontuais e gerenciamento de mídias sociais. Temos muito a agradecer pelos serviços prestados.","LC","Lucas C.","Comunicação — Vai-Vai"),
            ("ultra","Conheci a Digify em um momento crítico do meu e-commerce. O time não só resolveu os problemas como melhorou demais a performance do site. Recomendo sem hesitar.","TM","Távio M.","CEO — TMiranda"),
            ("cyan","Utilizamos a Digify para criação de sites, integrações, SEO e tráfego pago. Um parceiro que entende de negócios digitais de verdade. Recomendo a qualquer empresa.","LF","Lucas F.","CEO — Rache Aqui"),
            ("violet","Como iniciante no marketing digital, foi fundamental o trabalho da Digify para estruturar meu site, funis de venda e anúncios no Google. Profissionais incríveis!","VZ","Vinícius Z.","Dir. de Vendas — HiperSkin")],
  "blog": True,
  "blog_eyebrow":"Conteúdo","blog_h":"O que está acontecendo.","blog_cta":"Ver todos os artigos",
  "posts":[("violet","Marketing Digital","Google Ads: crie anúncios que convertem e impulsionam vendas","Estratégias para transformar clique em cliente e otimizar campanhas que realmente pagam a conta.","2026-07-23","23 de julho de 2026","/blog/google-ads-crie-anuncios-que-convertem-e-impulsionam-vendas/"),
           ("jade","SEO","O poder das palavras-chave de cauda longa em SEO","Como encontrar e usar termos de cauda longa para atrair tráfego orgânico mais qualificado.","2026-07-21","21 de julho de 2026","/blog/descubra-o-poder-das-palavras-chave-de-cauda-longa-em-seo/"),
           ("violet","Marketing Digital","Estratégia de conteúdo: gere leads qualificados para o seu negócio","Táticas comprovadas para atrair, engajar e converter visitantes em oportunidades reais.","2026-07-20","20 de julho de 2026","/blog/estrategia-de-conteudo-gere-leads-qualificados-para-seu-negocio/")],
  "faq_eyebrow":"Dúvidas frequentes","faq_h":"Sem letra miúda.",
  "faq":[("Quanto tempo leva para criar um site?","Uma landing page fica pronta em cerca de 10 dias úteis. Um site institucional completo costuma levar de 3 a 5 semanas, e um e-commerce ou sistema, de 6 a 10 semanas. O prazo exato sai no planejamento, depois do diagnóstico — e a partir daí ele vira compromisso, com cronograma visível para você acompanhar."),
         ("Quanto custa um projeto com a Digify?","O valor depende do escopo, e por isso não trabalhamos com tabela fixa. Fazemos um diagnóstico gratuito, entendemos o objetivo do projeto e enviamos uma proposta com escopo fechado, prazo e valor. Se o orçamento não fizer sentido para o momento da empresa, dizemos isso antes de você investir tempo."),
         ("Em quanto tempo o SEO começa a dar resultado?","Os primeiros sinais — indexação, ganho de posição em termos de cauda longa e aumento de impressões — costumam aparecer entre 60 e 90 dias. Resultado consolidado em termos competitivos leva de 6 a 12 meses. SEO é ativo, não anúncio: o retorno é cumulativo e continua rendendo depois que o investimento para."),
         ("Vocês dão manutenção depois da entrega?","Sim. Todo projeto inclui um período de acompanhamento pós-lançamento, e oferecemos planos mensais de manutenção que cobrem atualizações, backup, monitoramento de performance e pequenos ajustes de conteúdo. Você não fica com um site parado seis meses depois do deploy."),
         ("Com quais tecnologias vocês trabalham?","Escolhemos a stack pelo problema, não por preferência. Usamos WordPress e WooCommerce quando o cliente precisa de autonomia editorial, sites estáticos quando performance e SEO são prioridade absoluta, e desenvolvimento sob medida em PHP, Python e JavaScript quando o projeto envolve integrações e regras de negócio próprias."),
         ("Vocês atendem empresas de fora de São Paulo?","Sim. Trabalhamos de forma remota com clientes em todo o Brasil e também no exterior. Todo o processo — diagnóstico, alinhamentos, entregas e acompanhamento — funciona por videochamada, WhatsApp e acesso ao ambiente do projeto.")],
  "cta_eyebrow":"Próximo passo","cta_h":"Vamos começar pelo diagnóstico.",
  "cta_lede":"Conte o que você precisa. Respondemos em até um dia útil com um diagnóstico do cenário atual e os caminhos possíveis — sem compromisso e sem apresentação de 40 slides.",
  "cta_steps":["Você envia o contexto do projeto.","Analisamos o site, os concorrentes e o mercado.","Você recebe o diagnóstico e a proposta com escopo fechado."],
  "cta_wa":"Prefiro falar no WhatsApp",
  "f_name":"Nome","f_name_ph":"Seu nome","f_comp":"Empresa","f_comp_ph":"Nome da empresa",
  "f_mail":"E-mail","f_mail_ph":"voce@empresa.com.br","f_wa":"WhatsApp","f_wa_ph":"(11) 90000-0000",
  "f_need":"O que você precisa","f_need_ph":"Selecione um serviço",
  "f_needs":["Criação de site","Desenvolvimento de app","SEO","Marketing digital / tráfego pago","E-commerce","Sistema ou integração","Ainda não sei"],
  "f_budget":"Investimento previsto","f_budget_ph":"Selecione uma faixa",
  "f_budgets":["Até R$ 5 mil","R$ 5 mil a R$ 15 mil","R$ 15 mil a R$ 40 mil","Acima de R$ 40 mil","Preciso de ajuda para definir"],
  "f_msg":"Contexto do projeto","f_msg_ph":"Conte rapidamente o cenário atual e o que você quer alcançar.",
  "f_send":"Enviar e receber o diagnóstico",
  "f_note":"Resposta em até 1 dia útil. Seus dados não são compartilhados com terceiros.",
  "f_hp":"Não preencha:",
  "ft_about":"Agência web especialista em criação de sites, sistemas sob medida e SEO. Mais de 10 anos levando empresas ao topo do Google.",
  "ft_svc":"Serviços","ft_comp":"Empresa","ft_contact":"Contato",
  "ft_links":[("/portfolio/","Portfólio"),("/sobre/","Sobre a Digify"),("/blog/","Blog"),("/contato/","Contato"),("https://plugins.digify.live/","Plugins WordPress"),("/politica-de-privacidade/","Política de privacidade")],
  "ft_rights":"© 2026 Digify Marketing Digital. Todos os direitos reservados.",
  "ft_priv":"Privacidade","ft_map":"Sitemap",
  "wa_label":"Falar no WhatsApp",
  "area":"Brasil",
}

# ---------------------------------------------------------------- EN
EN = {
  "code":"en","short":"EN","dir":"en/","og":"en_US",
  "title":"Digify | Web Development, Custom Software & SEO Agency",
  "desc":"Nearshore web agency in Brazil. Websites, custom systems and SEO for companies that want to be found first. 10+ years, 300+ projects delivered.",
  "form_name":"proposal-en",
  "wa_text":"Hi%2C+I%27d+like+a+free+diagnosis",
  "skip":"Skip to content",
  "nav":[("#servicos","Services"),("#processo","Process"),("#faq","FAQ"),("#proposta","Contact")],
  "cta_nav":"Request a proposal",
  "menu_open":"Open menu","menu_close":"Close menu",
  "sw_label":"Turn the site's light on or off","sw_title":"Lights on / off",
  "lang_label":"Site language",
  "tablist":"Digify highlights",
  "slides":[
    {"c":"flame","c2":"ultra",
     "eyebrow":"Full-stack web agency · Working worldwide",
     "h":"The <em class=\"hl\">first</em> result takes almost everything.",
     "tag":"h1",
     "lede":"Right now, someone is searching for exactly what you sell. We handle technical SEO, content and authority so the answer is your site — not your competitor's.",
     "cta1":"Request a proposal","cta2":"How we do SEO","cta2_href":"#servicos",
     "facts":[("#1–3","organic ranking"),("+340%","traffic in 12 months"),("300+","projects delivered")],
     "panel":"rank",
     "p_query":"what you sell + your city","p_you":"Your company","p_tag":"position 1",
     "p_cap":"Average organic position of Digify clients: #1 to #3 within the first six months of an engagement."},
    {"c":"cyan","c2":"jade",
     "eyebrow":"Custom systems · APIs · Automation",
     "h":"Bring the idea. We hand back the <em class=\"hl\">whole system</em>.",
     "tag":"h2",
     "lede":"You describe the problem in plain language, not in technical specs. We design the architecture, write the code, connect it to what you already run and ship it — with a delivery every week so you can follow along.",
     "cta1":"I need a system","cta2":"See how it works","cta2_href":"#servicos",
     "facts":[("6 weeks","to the first MVP"),("Weekly","delivery cycle"),("100%","of the code is yours")],
     "panel":"build",
     "p_top":"brief received",
     "p_idea":"“I need orders and inventory in one place, and invoices issued without retyping anything.”",
     "p_mods":["Orders","Inventory","Invoicing","Reports","ERP integration","Roles & access"],
     "p_cap":"Architecture, code, tests and deployment. You track progress in real time."},
    {"c":"violet","c2":"pink",
     "eyebrow":"Website design · Built from scratch",
     "h":"Your site, your way. Live in <em class=\"hl\">record time</em>.",
     "tag":"h2",
     "lede":"No off-the-shelf template with your logo dropped in. We design from scratch, in your brand's voice, with the structure your business actually needs. Fast because the process has run 300+ times — not because we cut corners.",
     "cta1":"I need a website","cta2":"See the process","cta2_href":"#processo",
     "facts":[("10 days","for a landing page live"),("98/100","average PageSpeed score"),("Zero","recycled templates")],
     "panel":"site",
     "p_url":"yourdomain.com","p_cap":"your identity, not ours"},
  ],
  "tabs":[("01 · SEO","Outrank your competition"),
          ("02 · Systems","From idea to full system"),
          ("03 · Websites","Your way, in record time")],
  "logos_label":"Companies that trust Digify",
  "nums_eyebrow":"Results","nums_h":"Numbers, not adjectives.",
  "nums":[("flame","#1–3","Average organic position","Within the first six months of an SEO engagement."),
          ("ultra","+340%","Traffic growth","Average across SEO projects over 12 months."),
          ("jade","98/100","PageSpeed score","Average across the sites we ship.")],
  "svc_eyebrow":"What we do","svc_h":"Six disciplines, one goal.",
  "svc_lede":"Every project starts with the business problem — not with a service menu.",
  "svc_cta":"Tell us about your case","svc_go":"Learn more",
  "svcs":[("flame","Websites","Website development","#proposta","Corporate sites, landing pages and stores that load fast, work everywhere and are built to turn visits into customers."),
          ("ultra","Apps","Mobile app development","#proposta","iOS and Android apps with intuitive design and API integration. From MVP to finished product, with weekly releases."),
          ("jade","SEO","SEO agency","#proposta","Technical audits, content, link building and rank tracking. SEO that puts you in front of people already searching."),
          ("violet","Paid media","Digital marketing","#proposta","Google Ads, Meta Ads and organic growth working together to bring in qualified leads and defend your ROI."),
          ("pink","E-commerce","Online stores","#proposta","High performance, conversion-focused UX, marketplace integration and every major payment method."),
          ("cyan","Systems","Systems & integrations","#proposta","Custom web systems, APIs and automations that remove manual work and let the business scale without growing headcount.")],
  "proc_eyebrow":"How we work","proc_h":"Discovery. Plan. Code. Growth.",
  "steps":[("Discovery","We learn the business, the market and the competition before proposing anything. No off-the-shelf formula."),
           ("Planning","Scope, stack, timeline and metrics agreed upfront. You know exactly what to expect and when."),
           ("Build","Development with weekly updates and live access to progress. No black box."),
           ("Growth","We launch, measure and optimise. The project doesn't end at deploy — that's where it starts.")],
  "quo_eyebrow":"Clients","quo_h":"People who've been here.","quo_stars":"5 out of 5",
  "quotes":[("flame","Vai-Vai has partnered with Digify for years. We've run all kinds of projects together, from websites to one-off campaigns and social media management. We have a lot to thank them for.","LC","Lucas C.","Communications — Vai-Vai"),
            ("ultra","I found Digify at a critical moment for my e-commerce. The team didn't just fix the problems — they made the site dramatically faster. I recommend them without hesitation.","TM","Távio M.","CEO — TMiranda"),
            ("cyan","We've worked with Digify on websites, integrations, SEO and paid traffic. A partner that genuinely understands digital business. I'd recommend them to any company.","LF","Lucas F.","CEO — Rache Aqui"),
            ("violet","As a newcomer to digital marketing, Digify's work was essential in structuring my site, sales funnels and Google campaigns. Incredible professionals.","VZ","Vinícius Z.","Sales Director — HiperSkin")],
  "blog": False,
  "faq_eyebrow":"FAQ","faq_h":"No fine print.",
  "faq":[("How long does it take to build a website?","A landing page takes around 10 business days. A full corporate site usually runs 3 to 5 weeks, and an e-commerce store or custom system, 6 to 10 weeks. The exact timeline comes out of the planning phase, right after discovery — and from that point it becomes a commitment, with a schedule you can follow."),
         ("How much does a Digify project cost?","It depends on scope, which is why we don't publish a price list. We run a free diagnosis, understand what the project needs to achieve, and send a proposal with fixed scope, timeline and price. If the budget doesn't make sense for where your company is right now, we'll say so before you invest any more time."),
         ("How long until SEO shows results?","The first signals — indexing, long-tail ranking gains and rising impressions — usually appear within 60 to 90 days. Consolidated results on competitive terms take 6 to 12 months. SEO is an asset, not an ad: the return compounds and keeps paying after you stop investing."),
         ("Do you provide maintenance after launch?","Yes. Every project includes a post-launch support window, and we offer monthly maintenance plans covering updates, backups, performance monitoring and small content changes. You won't be left with a site that quietly rots six months after deploy."),
         ("What technologies do you work with?","We pick the stack based on the problem, not on preference. WordPress and WooCommerce when the client needs editorial autonomy, static sites when performance and SEO are the top priority, and custom development in PHP, Python and JavaScript when the project involves integrations and business rules of its own."),
         ("Do you work with clients outside Brazil?","Yes. We work remotely with clients across the Americas and Europe. Discovery, check-ins, deliveries and support all run over video calls, chat and shared access to the project environment. Our team is based in Brazil, which overlaps with US business hours — one of the reasons clients use us as a nearshore option.")],
  "cta_eyebrow":"Next step","cta_h":"Let's start with the diagnosis.",
  "cta_lede":"Tell us what you need. We reply within one business day with a read on where you stand today and the routes available — no commitment, no 40-slide deck.",
  "cta_steps":["You send the context of the project.","We analyse your site, your competitors and the market.","You get the diagnosis and a fixed-scope proposal."],
  "cta_wa":"I'd rather talk on WhatsApp",
  "f_name":"Name","f_name_ph":"Your name","f_comp":"Company","f_comp_ph":"Company name",
  "f_mail":"Email","f_mail_ph":"you@company.com","f_wa":"Phone / WhatsApp","f_wa_ph":"+1 555 000 0000",
  "f_need":"What you need","f_need_ph":"Select a service",
  "f_needs":["Website","Mobile app","SEO","Digital marketing / paid traffic","E-commerce","System or integration","Not sure yet"],
  "f_budget":"Expected investment","f_budget_ph":"Select a range",
  "f_budgets":["Up to US$ 2,000","US$ 2,000 – 6,000","US$ 6,000 – 15,000","Over US$ 15,000","Help me figure it out"],
  "f_msg":"Project context","f_msg_ph":"Briefly: where you are today and what you want to achieve.",
  "f_send":"Send and get my diagnosis",
  "f_note":"Reply within one business day. We never share your data with third parties.",
  "f_hp":"Leave this empty:",
  "ft_about":"Full-stack web agency specialising in websites, custom systems and SEO. Over 10 years taking companies to the top of Google.",
  "ft_svc":"Services","ft_comp":"Company","ft_contact":"Contact",
  "ft_links":[("#faq","FAQ"),("https://plugins.digify.live/","WordPress plugins"),("/blog/","Blog (in Portuguese)"),("/politica-de-privacidade/","Privacy policy")],
  "ft_rights":"© 2026 Digify Marketing Digital. All rights reserved.",
  "ft_priv":"Privacy","ft_map":"Sitemap",
  "wa_label":"Talk on WhatsApp",
  "area":"Worldwide",
}

# ---------------------------------------------------------------- ES
ES = {
  "code":"es","short":"ES","dir":"es/","og":"es_ES",
  "title":"Digify | Agencia de Desarrollo Web, Software a Medida y SEO",
  "desc":"Agencia web full-stack en Brasil. Sitios web, sistemas a medida y SEO para empresas que quieren aparecer primero. Más de 10 años y 300 proyectos.",
  "form_name":"propuesta-es",
  "wa_text":"Hola%2C+quiero+un+diagn%C3%B3stico+gratuito",
  "skip":"Ir al contenido",
  "nav":[("#servicos","Servicios"),("#processo","Proceso"),("#faq","FAQ"),("#proposta","Contacto")],
  "cta_nav":"Solicitar propuesta",
  "menu_open":"Abrir menú","menu_close":"Cerrar menú",
  "sw_label":"Encender o apagar la luz del sitio","sw_title":"Encender / apagar",
  "lang_label":"Idioma del sitio",
  "tablist":"Destacados de Digify",
  "slides":[
    {"c":"flame","c2":"ultra",
     "eyebrow":"Agencia web full-stack · Alcance global",
     "h":"El <em class=\"hl\">primer</em> resultado se lleva casi todo.",
     "tag":"h1",
     "lede":"Mientras lees esto, alguien está buscando exactamente lo que vendes. Hacemos SEO técnico, contenido y autoridad para que la respuesta sea tu sitio — y no el de tu competencia.",
     "cta1":"Solicitar propuesta","cta2":"Cómo hacemos SEO","cta2_href":"#servicos",
     "facts":[("#1–3","posición orgánica"),("+340%","tráfico en 12 meses"),("300+","proyectos entregados")],
     "panel":"rank",
     "p_query":"lo que vendes + tu ciudad","p_you":"Tu empresa","p_tag":"posición 1",
     "p_cap":"Posición orgánica media de los clientes de Digify: entre #1 y #3 en los primeros seis meses del proyecto."},
    {"c":"cyan","c2":"jade",
     "eyebrow":"Sistemas a medida · APIs · Automatización",
     "h":"Tráenos la idea. Te devolvemos el <em class=\"hl\">sistema completo</em>.",
     "tag":"h2",
     "lede":"Nos describes el problema en palabras normales, no en requisitos técnicos. Nosotros diseñamos la arquitectura, escribimos el código, lo integramos con lo que ya usas y lo publicamos — con una entrega cada semana para que sigas el avance.",
     "cta1":"Quiero mi sistema","cta2":"Ver cómo funciona","cta2_href":"#servicos",
     "facts":[("6 sem.","hasta el primer MVP"),("Semanal","ciclo de entrega"),("100%","del código es tuyo")],
     "panel":"build",
     "p_top":"briefing recibido",
     "p_idea":"«Necesito controlar pedidos e inventario en un solo lugar, y emitir facturas sin volver a teclear nada.»",
     "p_mods":["Pedidos","Inventario","Facturación","Informes","Integración ERP","Accesos y perfiles"],
     "p_cap":"Arquitectura, código, pruebas y despliegue. Sigues el progreso en tiempo real."},
    {"c":"violet","c2":"pink",
     "eyebrow":"Diseño de sitios web · Hecho desde cero",
     "h":"Tu sitio, a tu manera. En línea en <em class=\"hl\">tiempo récord</em>.",
     "tag":"h2",
     "lede":"Nada de plantillas prehechas con el logo cambiado. Diseñamos desde cero, con la voz de tu marca y la estructura que tu negocio realmente necesita. Rápido porque el proceso ya se repitió más de 300 veces — no porque tomemos atajos.",
     "cta1":"Quiero mi sitio","cta2":"Ver el proceso","cta2_href":"#processo",
     "facts":[("10 días","para una landing en línea"),("98/100","nota media en PageSpeed"),("Cero","plantillas reutilizadas")],
     "panel":"site",
     "p_url":"tudominio.com","p_cap":"tu identidad, no la nuestra"},
  ],
  "tabs":[("01 · SEO","Aparecer antes que tu competencia"),
          ("02 · Sistemas","De la idea al sistema completo"),
          ("03 · Sitios","A tu manera, en tiempo récord")],
  "logos_label":"Empresas que confían en Digify",
  "nums_eyebrow":"Resultados","nums_h":"Números, no adjetivos.",
  "nums":[("flame","#1–3","Posición orgánica media","En los primeros 6 meses de un proyecto de SEO."),
          ("ultra","+340%","Crecimiento de tráfico","Media de los proyectos de SEO en 12 meses."),
          ("jade","98/100","Nota en PageSpeed","Media de los sitios que entregamos.")],
  "svc_eyebrow":"Qué hacemos","svc_h":"Seis frentes, un objetivo.",
  "svc_lede":"Cada proyecto empieza por el problema del negocio — no por el catálogo de servicios.",
  "svc_cta":"Contarnos mi caso","svc_go":"Saber más",
  "svcs":[("flame","Sitios","Creación de sitios web","#proposta","Sitios corporativos, landing pages y tiendas ultrarrápidas, responsivas y diseñadas para convertir visitas en clientes."),
          ("ultra","Apps","Desarrollo de apps","#proposta","Aplicaciones iOS y Android con diseño intuitivo e integración con APIs. Del MVP al producto final, con entregas semanales."),
          ("jade","SEO","Agencia SEO","#proposta","Auditoría técnica, contenido, link building y seguimiento de posiciones. SEO que te pone delante de quien ya está buscando."),
          ("violet","Medios pagos","Marketing digital","#proposta","Google Ads, Meta Ads y crecimiento orgánico trabajando juntos para atraer clientes calificados y defender el ROI."),
          ("pink","E-commerce","Tiendas online","#proposta","Alto rendimiento, UX optimizada para conversión, integración con marketplaces y todos los medios de pago principales."),
          ("cyan","Sistemas","Sistemas e integraciones","#proposta","Sistemas web a medida, APIs y automatizaciones que eliminan trabajo manual y permiten escalar sin inflar el equipo.")],
  "proc_eyebrow":"Cómo trabajamos","proc_h":"Diagnóstico. Plan. Código. Crecimiento.",
  "steps":[("Diagnóstico","Entendemos el negocio, el mercado y la competencia antes de proponer cualquier solución. Sin fórmulas prehechas."),
           ("Planificación","Alcance, tecnología, cronograma e indicadores definidos. Sabes exactamente qué esperar y cuándo."),
           ("Ejecución","Desarrollo con actualizaciones semanales y acceso al avance en tiempo real, sin caja negra."),
           ("Crecimiento","Lanzamos, medimos y optimizamos. El proyecto no termina en el despliegue — ahí es donde empieza.")],
  "quo_eyebrow":"Clientes","quo_h":"Quienes ya pasaron por aquí.","quo_stars":"5 de 5",
  "quotes":[("flame","Vai-Vai trabaja con Digify desde hace años. Hicimos proyectos de todo tipo, desde sitios web hasta campañas puntuales y gestión de redes sociales. Tenemos mucho que agradecerles.","LC","Lucas C.","Comunicación — Vai-Vai"),
            ("ultra","Conocí a Digify en un momento crítico de mi e-commerce. El equipo no solo resolvió los problemas: mejoró muchísimo el rendimiento del sitio. Los recomiendo sin dudar.","TM","Távio M.","CEO — TMiranda"),
            ("cyan","Trabajamos con Digify en sitios web, integraciones, SEO y tráfico pago. Un socio que entiende de verdad el negocio digital. Se lo recomiendo a cualquier empresa.","LF","Lucas F.","CEO — Rache Aqui"),
            ("violet","Como principiante en marketing digital, el trabajo de Digify fue fundamental para estructurar mi sitio, los embudos de venta y los anuncios en Google. ¡Profesionales increíbles!","VZ","Vinícius Z.","Dir. de Ventas — HiperSkin")],
  "blog": False,
  "faq_eyebrow":"Preguntas frecuentes","faq_h":"Sin letra pequeña.",
  "faq":[("¿Cuánto tarda la creación de un sitio web?","Una landing page está lista en unos 10 días hábiles. Un sitio corporativo completo suele tomar de 3 a 5 semanas, y un e-commerce o sistema, de 6 a 10 semanas. El plazo exacto sale en la planificación, después del diagnóstico — y a partir de ahí se convierte en compromiso, con un cronograma que puedes seguir."),
         ("¿Cuánto cuesta un proyecto con Digify?","Depende del alcance, por eso no publicamos una lista de precios. Hacemos un diagnóstico gratuito, entendemos el objetivo del proyecto y enviamos una propuesta con alcance cerrado, plazo y precio. Si el presupuesto no tiene sentido para el momento de tu empresa, te lo decimos antes de que inviertas más tiempo."),
         ("¿En cuánto tiempo el SEO da resultados?","Las primeras señales — indexación, avances en términos de cola larga y aumento de impresiones — suelen aparecer entre 60 y 90 días. El resultado consolidado en términos competitivos toma de 6 a 12 meses. El SEO es un activo, no un anuncio: el retorno es acumulativo y sigue rindiendo después de que la inversión para."),
         ("¿Dan mantenimiento después de la entrega?","Sí. Todo proyecto incluye un periodo de acompañamiento posterior al lanzamiento, y ofrecemos planes mensuales de mantenimiento con actualizaciones, copias de seguridad, monitoreo de rendimiento y ajustes de contenido. No te quedas con un sitio abandonado seis meses después."),
         ("¿Con qué tecnologías trabajan?","Elegimos el stack según el problema, no por preferencia. WordPress y WooCommerce cuando el cliente necesita autonomía editorial, sitios estáticos cuando el rendimiento y el SEO son prioridad absoluta, y desarrollo a medida en PHP, Python y JavaScript cuando el proyecto involucra integraciones y reglas de negocio propias."),
         ("¿Atienden clientes fuera de Brasil?","Sí. Trabajamos de forma remota con clientes en toda América Latina, España y Estados Unidos. Diagnóstico, reuniones, entregas y soporte funcionan por videollamada, chat y acceso compartido al entorno del proyecto. Nuestro equipo está en Brasil, con horario compatible con casi toda la región.")],
  "cta_eyebrow":"Siguiente paso","cta_h":"Empecemos por el diagnóstico.",
  "cta_lede":"Cuéntanos qué necesitas. Respondemos en un día hábil con un diagnóstico de la situación actual y los caminos posibles — sin compromiso y sin una presentación de 40 diapositivas.",
  "cta_steps":["Nos envías el contexto del proyecto.","Analizamos tu sitio, tu competencia y el mercado.","Recibes el diagnóstico y la propuesta con alcance cerrado."],
  "cta_wa":"Prefiero hablar por WhatsApp",
  "f_name":"Nombre","f_name_ph":"Tu nombre","f_comp":"Empresa","f_comp_ph":"Nombre de la empresa",
  "f_mail":"Correo","f_mail_ph":"tu@empresa.com","f_wa":"Teléfono / WhatsApp","f_wa_ph":"+52 55 0000 0000",
  "f_need":"Qué necesitas","f_need_ph":"Selecciona un servicio",
  "f_needs":["Sitio web","Aplicación móvil","SEO","Marketing digital / tráfico pago","E-commerce","Sistema o integración","Todavía no lo sé"],
  "f_budget":"Inversión prevista","f_budget_ph":"Selecciona un rango",
  "f_budgets":["Hasta US$ 2.000","US$ 2.000 – 6.000","US$ 6.000 – 15.000","Más de US$ 15.000","Necesito ayuda para definirlo"],
  "f_msg":"Contexto del proyecto","f_msg_ph":"En resumen: dónde estás hoy y qué quieres lograr.",
  "f_send":"Enviar y recibir el diagnóstico",
  "f_note":"Respuesta en 1 día hábil. Nunca compartimos tus datos con terceros.",
  "f_hp":"No rellenar:",
  "ft_about":"Agencia web full-stack especializada en sitios web, sistemas a medida y SEO. Más de 10 años llevando empresas al primer lugar de Google.",
  "ft_svc":"Servicios","ft_comp":"Empresa","ft_contact":"Contacto",
  "ft_links":[("#faq","Preguntas frecuentes"),("https://plugins.digify.live/","Plugins WordPress"),("/blog/","Blog (en portugués)"),("/politica-de-privacidade/","Política de privacidad")],
  "ft_rights":"© 2026 Digify Marketing Digital. Todos los derechos reservados.",
  "ft_priv":"Privacidad","ft_map":"Sitemap",
  "wa_label":"Hablar por WhatsApp",
  "area":"Global",
}

LANGS = [PT, EN, ES]
